### ISSUE TITLE
5号機のオレンジ色検出について

### ISSUE THREAD

**Issue by marubashi11** [CIR-KIT/WholeIssue#2]
@RyodoTanaka  

CIR-KIT1年の丸橋です。
現状5号機で使われる予定のカメラを使ってオレンジ色検出テストをしてみたところ、5m以上離れたところからの検出が困難であることがわかりました。精度の高い検出をするために、

- つくばチャレンジで使われるオレンジ色のジャケット
- 新しいカメラ
- 新しいLRF

が必要です。
唐突ですみませんが至急用意して頂きたく思います。

**Comment by RyodoTanaka** [comment]
@marubashi11 
了解です！
すべて研究室にあるので，申し訳ないけど誰か取りに来てくれると助かります．
よろしくお願いしますm(_ _)m

**Comment by marubashi11** [comment]
すべて受け取りました。
新しいカメラでテストしてみたところ、オレンジ色検出の精度が飛躍的に向上しました。
どうもありがとうございました。

**Comment by yasu80** [comment]
@RyodoTanaka 

ありがとうございました！
