### ISSUE TITLE
ROS2やりたい

### ISSUE THREAD

**Issue by forno** [CIR-KIT/WholeIssue#3]
ROS2 でのDDS通信の最適化や，複数のロボットの協調動作向けの改良などを活かして，
複数のロボットのデータの融通に対しての改良を行いたい．

ひとまずros1_bridgeの使い方からでもよいかなと思うので，ROS2化を目指しませんか？
という提案．

**Comment by RyodoTanaka** [comment]
4号機は引き継いで開発してるよ...！

**Comment by RyodoTanaka** [comment]
ROS2化も進めてるよ...！

**Comment by forno** [comment]
あらら

とはいえいつまでもうちが開いた状態のIssueあるとちょっと大変なので必要なら再度開いてくださいまし…！
コメントもついていなかったので，お願いします
